### PR TITLE
Fix glider names

### PR DESCRIPTION
**Pull request by ocefpaf**
@MathewBiddle, this fix an issue reported by Mary Solokas (I'm not sure what is Mary's GitHub handle). After review/merge we should issued a new release.

### CODE REVIEW

**Comment by MathewBiddle** [comment]
I think this is the change your proposing in `ioos_metrics.py`?

https://github.com/ioos/ioos_metrics/pull/90/files#diff-c1e3298f59885519b1b10f023299eae49fedc0616aaf818f2155ed5a11a5371b

**Comment by ocefpaf** [comment]
> I think this is the change your proposing in `ioos_metrics.py`?
> 
> https://github.com/ioos/ioos_metrics/pull/90/files#diff-c1e3298f59885519b1b10f023299eae49fedc0616aaf818f2155ed5a11a5371b

Yep. That is the main part of this PR. The rest is mostly lint auto-updates.

**Comment by MathewBiddle** [comment]
Okay. That change looks good. 

I ran into another issue with the [IOOS_BTN.ipynb](https://github.com/ioos/ioos_metrics/blob/main/notebooks/IOOS_BTN.ipynb):

image


Looks like `.append` has been deprecated since pandas 1.4: https://pandas.pydata.org/pandas-docs/version/1.4/reference/api/pandas.DataFrame.append.html

Here is what I'm running:
```python
>>pd.__version__
'2.2.1'
```

Suggest changing to `pd.concat`:
```python
if today not in ioos_btn_df["date_UTC"].to_list():
    ioos_btn_df = pd.concat([ioos_btn_df, pd.DataFrame({"date_UTC": [today]})])
```

**Comment by ocefpaf** [comment]
> I ran into another issue with the [IOOS_BTN.ipynb](https://github.com/ioos/ioos_metrics/blob/main/notebooks/IOOS_BTN.ipynb)

Do you want to fix that in this PR? Is that version of the notebook that uses the ioos_metrics library?

**Comment by MathewBiddle** [comment]
ah, good point. I got confused. Nah, lets fix that when we get around to https://github.com/ioos/ioos_metrics/issues/35

**Comment by MathewBiddle** [comment]
I should have been testing with https://github.com/ioos/ioos_metrics/blob/main/notebooks/run_metrics.ipynb. 

Still looks good. Merging.

**Comment by ocefpaf** [comment]
> I should have been testing with https://github.com/ioos/ioos_metrics/blob/main/notebooks/run_metrics.ipynb.

The renaming of that one to IOOS_BTN.ipynb is still pending your approval 😬

**Pull request merged**
